### ISSUE TITLE
Crossplat demo does not work on Linux

### ISSUE THREAD

**Issue by art-ist** [chromelyapps/demo-projects#29]
When trying to run the crossplat demo on Ubuntu 20.04, it compiles without errors but fails to start.

``` bash
$ dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 16 sec for /app/CrossPlatDemo.csproj.
  CrossPlatDemo -> /app/bin/Debug/netcoreapp3.1/linux-x64/crossplatdemo.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:18.21

$ dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libgdk-3.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdk-3.so.0: cannot open shared object file: No such file or directory
   at Chromely.NativeHost.InteropLinux.gdk_set_allowed_backends(String backend)
   at Chromely.NativeHost.ChromelyLinuxHost..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at Chromely.Core.ChromelyApp.RegisterControllerRoutes(ServiceProvider serviceProvider)
   at Chromely.Core.AppBuilder.Build()
   at CrossPlatDemo.Demo.Program.Main(String[] args) in /app/Program.cs:line 27

```
Running prepends this
```bash
$ LD_DEBUG=libs dotnet run
      8734:	find library=libpthread.so.0 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libpthread.so.0
      8734:	
      8734:	find library=libdl.so.2 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libdl.so.2
      8734:	
      8734:	find library=libc.so.6 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libc.so.6
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libpthread.so.0
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libc.so.6
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libdl.so.2
      8734:	
      8734:	
      8734:	initialize program: docker
      8734:	
      8734:	
      8734:	transferring control: docker
      8734:	
      8734:	find library=libnss_compat.so.2 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libnss_compat.so.2
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libnss_compat.so.2
      8734:	
      8734:	find library=libnss_nis.so.2 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libnss_nis.so.2
      8734:	
      8734:	find library=libnsl.so.1 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libnsl.so.1
      8734:	
      8734:	find library=libnss_files.so.2 [0]; searching
      8734:	 search cache=/etc/ld.so.cache
      8734:	  trying file=/lib/x86_64-linux-gnu/libnss_files.so.2
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libnss_files.so.2
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libnsl.so.1
      8734:	
      8734:	
      8734:	calling init: /lib/x86_64-linux-gnu/libnss_nis.so.2
``` 
before showing the stack trace above.

Any ideas, what I'm missing?

**Comment by mattkol** [comment]
@art-ist 

Your Ubuntu 20.04 distro is either not properly setup for gtk3 or you need to create a symlink to libgdk-3.so.0

````
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libgdk-3.so.0' or one of its dependencies. In 
````

Maybe this ..
> Do you have an older version of libgtk-3 installed? You could check if the symlinks are correct. libgtk-3.so.0 should be a symlink, check where it points with ls -l /usr/lib/libgtk-3.so.0

from: https://stackoverflow.com/questions/14993659/ubuntu-12-10-libgtk-3-0-missing-symbols
